In [32]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [33]:
# Checking the versions of packages
print('Numpy Version : ',np.__version__)
print('Pandas Version : ',pd.__version__)
print('Seaborn Version : ',sns.__version__)

Numpy Version :  1.23.5
Pandas Version :  1.5.3
Seaborn Version :  0.12.2

In [34]:
# Importing the data from .csv file
df=pd.read_csv('/content/sample_data/Referral_Join_Prediction.csv')

In [35]:
# View the top 5 records
df.head()

,referral_id,referral_age,referral_exp_in_years,referral_preferred_city,referral_current_salary,referral_10_th_marks,referral_12th_marks,referral_graduation_marks,referral_post_grad_marks,referral_gender,referral_expected_sal,referral_aptitude_numerical_score,referral_aptitude_verbal_score,referral_aptitude_reasoning_score,referral_Management_Interview_score,referral_HR_Interview_score,Salary offered,Emp_Salary_Grade,Joined
0,1,28,5.0,Delhi,106,89.0,72,87.0,83.0,Male,123.0,10.00,33.04,?,10.0,3,141,EL0,Yes
1,2,26,3.0,Pune,65,63.0,77,94.0,85.0,Male,83.0,6.09,27.39,20.87,10.0,10,80,ML0,Yes
2,3,23,2.0,Mumbai,45,92.0,85,84.0,72.0,Male,62.0,41.74,2.61,40.00,2.0,1,60,EL0,No
3,4,29,6.0,Bangalore,126,60.0,95,95.0,67.0,Male,146.0,31.30,9.13,23.48,9.0,3,142,ML0,Yes
4,5,26,3.0,Mumbai,65,92.0,70,80.0,92.0,Female,83.0,25.65,30.43,16.52,7.0,4,89,EL0,Yes

In [36]:
# Checking the number of rows and columns in data set
print('No. of rows : ',df.shape[0])
print('No. of Columns : ',df.shape[1])

No. of rows :  499
No. of Columns :  19

In [37]:
# Checking the details of dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 499 entries, 0 to 498
Data columns (total 19 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   referral_id                          499 non-null    int64
 1   referral_age                         499 non-null    int64
 2   referral_exp_in_years                499 non-null    float64
 3   referral_preferred_city              499 non-null    object
 4   referral_current_salary              499 non-null    int64
 5   referral_10_th_marks                 498 non-null    float64
 6   referral_12th_marks                  499 non-null    int64
 7   referral_graduation_marks            498 non-null    float64
 8   referral_post_grad_marks             498 non-null    float64
 9   referral_gender                      499 non-null    object
 10  referral_expected_sal                497 non-null    float64
 11  referral_aptitude_numerical_score    496 non-null    object
 12  referral_aptitude_verbal_score       489 non-null    float64
 13  referral_aptitude_reasoning_score    495 non-null    object
 14  referral_Management_Interview_score  498 non-null    float64
 15  referral_HR_Interview_score          499 non-null    int64
 16  Salary offered                       499 non-null    int64
 17  Emp_Salary_Grade                     499 non-null    object
 18  Joined                               499 non-null    object
dtypes: float64(7), int64(6), object(6)
memory usage: 74.2+ KB

In [38]:
# Checking the data in more details
df.describe().T

,count,mean,std,min,25%,50%,75%,max
referral_id,499.0,250.000000,144.193157,1.00,125.50,250.00,374.50,499.00
referral_age,499.0,27.020040,2.811979,20.00,25.00,27.00,29.00,65.00
referral_exp_in_years,499.0,4.053307,2.609814,1.00,2.00,4.00,6.00,42.00
referral_current_salary,499.0,86.472946,52.566584,25.00,45.00,85.00,126.00,853.00
referral_10_th_marks,498.0,77.295181,11.128083,-1.00,68.00,78.00,87.00,103.00
referral_12th_marks,499.0,77.478958,10.932113,12.00,69.00,77.00,87.00,95.00
referral_graduation_marks,498.0,77.096386,10.812223,-1.00,68.00,77.00,86.00,104.00
referral_post_grad_marks,498.0,78.269076,10.478487,60.00,69.00,78.00,88.75,101.00
referral_expected_sal,497.0,108.692153,58.722281,40.00,62.00,103.00,143.00,870.00
referral_aptitude_verbal_score,489.0,21.840491,12.338425,0.43,11.74,20.87,32.61,43.48
referral_Management_Interview_score,498.0,5.732932,2.922706,1.00,3.00,6.00,8.00,10.00
referral_HR_Interview_score,499.0,5.651303,5.500516,1.00,3.00,5.00,8.00,111.00
Salary offered,499.0,102.006012,52.619704,40.00,60.00,101.00,141.00,868.00

In [39]:
# Dataset Observations
# 1. The dataset has records of 499 referals and 19 paramters
# There are missing values in
# (a) 'referral_10_th_marks',
# (b) 'referral_graduation_marks',
# (c) 'referral_post_grad_marks',
# (d) 'referral_expected_sal',
# (e) 'referral_aptitude_verbal_score'
# (f) 'referral_Management_Interview_score'
# (g) 'referral_aptitude_reasoning_score'
# 2. Need to check the data for referral_10_th_marks, referral_graduation_marks becuase it has -1
# 3. Need to check why object type for
# (a) referral_aptitude_numerical_score
# (b) referral_aptitude_reasoning_score

In [40]:
# Let check the unique values in referral_aptitude_numerical_score column becuase its data type is object
df['referral_aptitude_numerical_score'].unique()

array(['10.00', '6.09', '41.74', '31.30', '25.65', '38.70', '30.43',
       '5.65', '18.70', '23.04', '27.39', '28.26', '32.61', '40.00',
       '24.78', '0.87', '27.83', '18.26', '20.87', '6.52', '21.74',
       '4.78', '26.96', '39.13', '3.04', '13.48', '33.91', '3.48',
       '15.65', '13.91', '38.26', '3.91', '28.70', '23.48', '10.43',
       '8.26', '39.57', '7.39', '30.87', '5.22', '12.61', '16.96',
       '34.35', '33.04', '10.87', '4.35', '35.65', '16.52', '20.43',
       '36.52', '40.43', '7.83', '6.96', '22.17', '34.78', '33.48',
       '43.48', '0.43', '17.39', '9.13', '29.57', '19.13', '17.83',
       '37.83', '36.09', '23.91', '36.96', '19.57', '31.74', '22.61',
       '12.17', '37.39', '14.78', '30.00', '11.74', '35.22', '2.61',
       '40.87', '42.61', '29.13', '?', '9.57', '43.04', '13.04', '25.22',
       '1.74', '15.22', '11.30', '32.17', '14.35', '20.00', nan, '2.17',
       '26.52', '26.09', '1.30', '8.70', '41.30', '16.09', '42.17',
       '24.35'], dtype=object)

In [41]:
# Lets check the unique values in referral_aptitude_reasoning_score column becuase its data type is object
df['referral_aptitude_reasoning_score'].unique()

array(['?', '20.87', '40.00', '23.48', '16.52', '32.61', '18.26', '2.50',
       '36.52', '3.04', '38.70', '26.52', '22.61', '14.35', '0.87',
       '13.04', '39.13', '34.35', '43.48', '20.43', '25.22', '37.83',
       '3.91', '28.26', '15.22', '15.65', '35.22', '17.39', '24.78',
       '33.04', '42.61', '31.74', '21.74', '6.09', '2.17', '8.70',
       '41.30', '26.09', '23.91', '27.83', '9.57', '10.43', '40.87',
       '12.17', '6.96', '33.48', '12.61', '42.17', '6.52', '2.61',
       '23.04', '20.00', '7.39', '4.35', '25.65', '31.30', '30.43',
       '5.22', '10.00', '37.39', '27.39', '0.23', '26.96', '34.78',
       '13.48', '19.13', '8.26', '24.35', '21.30', '0.67', '0.99',
       '29.57', '78.00', '36.96', '19.57', '36.09', '38.26', '28.70',
       '69.67', '33.91', '10.87', '0.43', '89.00', '18.70', '13.91', nan,
       '32.17', '7.83', '40.43', '16.09', '43.04', '30.00', '39.57',
       '29.13', '41.74', '11.74', '22.17', '16.96', '3.48', '35.65',
       '30.87', '4.78', '1.74', '11.30', '9.13', '1.30', '5.65', '14.78'],
      dtype=object)

In [42]:
# As we have checked in above steps referral_aptitude_numerical_score and referral_aptitude_reasoning_score column has '?'
# We are replacing the ? with NULL

In [43]:
df['referral_aptitude_numerical_score']=df['referral_aptitude_numerical_score'].replace('?',np.NaN)
df['referral_aptitude_reasoning_score']=df['referral_aptitude_reasoning_score'].replace('?',np.NaN)

In [44]:
df['referral_aptitude_reasoning_score'].unique()

array([nan, '20.87', '40.00', '23.48', '16.52', '32.61', '18.26', '2.50',
       '36.52', '3.04', '38.70', '26.52', '22.61', '14.35', '0.87',
       '13.04', '39.13', '34.35', '43.48', '20.43', '25.22', '37.83',
       '3.91', '28.26', '15.22', '15.65', '35.22', '17.39', '24.78',
       '33.04', '42.61', '31.74', '21.74', '6.09', '2.17', '8.70',
       '41.30', '26.09', '23.91', '27.83', '9.57', '10.43', '40.87',
       '12.17', '6.96', '33.48', '12.61', '42.17', '6.52', '2.61',
       '23.04', '20.00', '7.39', '4.35', '25.65', '31.30', '30.43',
       '5.22', '10.00', '37.39', '27.39', '0.23', '26.96', '34.78',
       '13.48', '19.13', '8.26', '24.35', '21.30', '0.67', '0.99',
       '29.57', '78.00', '36.96', '19.57', '36.09', '38.26', '28.70',
       '69.67', '33.91', '10.87', '0.43', '89.00', '18.70', '13.91',
       '32.17', '7.83', '40.43', '16.09', '43.04', '30.00', '39.57',
       '29.13', '41.74', '11.74', '22.17', '16.96', '3.48', '35.65',
       '30.87', '4.78', '1.74', '11.30', '9.13', '1.30', '5.65', '14.78'],
      dtype=object)

In [45]:
# Change the data type of a column
df['referral_aptitude_numerical_score']=df['referral_aptitude_numerical_score'].astype('float64')
df['referral_aptitude_reasoning_score']=df['referral_aptitude_reasoning_score'].astype('float64')

In [46]:
# To verify the column data type is changed to float from object
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 499 entries, 0 to 498
Data columns (total 19 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   referral_id                          499 non-null    int64
 1   referral_age                         499 non-null    int64
 2   referral_exp_in_years                499 non-null    float64
 3   referral_preferred_city              499 non-null    object
 4   referral_current_salary              499 non-null    int64
 5   referral_10_th_marks                 498 non-null    float64
 6   referral_12th_marks                  499 non-null    int64
 7   referral_graduation_marks            498 non-null    float64
 8   referral_post_grad_marks             498 non-null    float64
 9   referral_gender                      499 non-null    object
 10  referral_expected_sal                497 non-null    float64
 11  referral_aptitude_numerical_score    495 non-null    float64
 12  referral_aptitude_verbal_score       489 non-null    float64
 13  referral_aptitude_reasoning_score    491 non-null    float64
 14  referral_Management_Interview_score  498 non-null    float64
 15  referral_HR_Interview_score          499 non-null    int64
 16  Salary offered                       499 non-null    int64
 17  Emp_Salary_Grade                     499 non-null    object
 18  Joined                               499 non-null    object
dtypes: float64(9), int64(6), object(4)
memory usage: 74.2+ KB

In [47]:
# To check the records who have 10th marks less than 33
df[df['referral_10_th_marks'] < 33]

,referral_id,referral_age,referral_exp_in_years,referral_preferred_city,referral_current_salary,referral_10_th_marks,referral_12th_marks,referral_graduation_marks,referral_post_grad_marks,referral_gender,referral_expected_sal,referral_aptitude_numerical_score,referral_aptitude_verbal_score,referral_aptitude_reasoning_score,referral_Management_Interview_score,referral_HR_Interview_score,Salary offered,Emp_Salary_Grade,Joined
89,90,27,4.0,Bangalore,85,-1.0,81,93.0,86.0,Female,103.0,31.74,6.52,30.43,10.0,3,101,EL0,Yes

In [48]:
# To check the records who have Graduation marks less than 33
df[df['referral_graduation_marks'] < 33]

,referral_id,referral_age,referral_exp_in_years,referral_preferred_city,referral_current_salary,referral_10_th_marks,referral_12th_marks,referral_graduation_marks,referral_post_grad_marks,referral_gender,referral_expected_sal,referral_aptitude_numerical_score,referral_aptitude_verbal_score,referral_aptitude_reasoning_score,referral_Management_Interview_score,referral_HR_Interview_score,Salary offered,Emp_Salary_Grade,Joined
270,271,29,6.0,Bangalore,126,82.0,88,-1.0,64.0,Male,143.0,10.43,27.39,27.83,1.0,6,141,ML0,No

In [49]:
# To impute the -1 value in 10th marks and Graduation marks with mean(average) score of all referals
marks_10 = df['referral_10_th_marks'].mean()
marks_10

77.29518072289157

In [28]:
marks_grad = df['referral_graduation_marks'].mean()
marks_grad

77.09638554216868

In [50]:
# To replace the -1 marks in 10th and graduation with calculated mean
df['referral_10_th_marks']=df['referral_10_th_marks'].replace(-1,marks_10)
df['referral_graduation_marks']=df['referral_graduation_marks'].replace(-1,marks_grad)

In [ ]:
df.iloc[89]

In [ ]:
df.iloc[270]

In [ ]:
df.info()

In [54]:
# Checking the object type columns in dataset
# referral_preferred_city
# referral_gender
# Emp_Salary_Grade
# Joined

In [55]:
df['referral_preferred_city'].value_counts()

Mumbai       232
Bangalore    142
Delhi         93
Pune          32
Name: referral_preferred_city, dtype: int64

In [60]:
df['referral_gender'].value_counts()

Male      260
Female    238
?           1
Name: referral_gender, dtype: int64

In [57]:
df['Emp_Salary_Grade'].value_counts()

EL0    221
ML0    187
EE0     91
Name: Emp_Salary_Grade, dtype: int64

In [ ]:
df['Joined'].value_counts()

In [ ]:
df['referral_gender'].mode()[0]

In [61]:
# To replace the ? in gender coloumn with mode value of gender column
df['referral_gender']=df['referral_gender'].replace('?',df['referral_gender'].mode()[0])

In [64]:
# Verifying the imputation is done
df['referral_gender'].value_counts()

Male      261
Female    238
Name: referral_gender, dtype: int64

In [ ]:
# Treatment of missing values
df.isnull().sum()

In [ ]:
sns.boxplot(data=df,x='referral_aptitude_verbal_score');

In [72]:
# As we have seen in box plot there are no outliers so we are imputing null values of referral_aptitude_verbal_score with mean score
df['referral_aptitude_verbal_score']=df['referral_aptitude_verbal_score'].fillna(df.referral_aptitude_verbal_score.mean())

In [ ]:
#Verifying the treatment of referral_aptitude_verbal_score
df.isnull().sum()

In [74]:
df['referral_10_th_marks']=df['referral_10_th_marks'].fillna(df.referral_10_th_marks.mean())
df['referral_graduation_marks']=df['referral_graduation_marks'].fillna(df.referral_graduation_marks.mean())
df['referral_post_grad_marks']=df['referral_post_grad_marks'].fillna(df.referral_post_grad_marks.mean())
df['referral_expected_sal']=df['referral_expected_sal'].fillna(df.referral_expected_sal.mean())
df['referral_aptitude_numerical_score']=df['referral_aptitude_numerical_score'].fillna(df.referral_aptitude_numerical_score.mean())
df['referral_aptitude_reasoning_score']=df['referral_aptitude_reasoning_score'].fillna(df.referral_aptitude_reasoning_score.mean())
df['referral_Management_Interview_score']=df['referral_Management_Interview_score'].fillna(df.referral_Management_Interview_score.mean())

In [76]:
# Checking the duplicates records in dataset
duplicate=df.duplicated()
print('Number of duplicate records %d' %(duplicate.sum()))

Number of duplicate records 0

In [78]:
# Incase if there are duplicate records, we drop/delete from dataframe
df.drop_duplicates(inplace=True)

In [ ]:
# Analysis
# 1. Univariate Analysis
# 2. Bivariate analysis
# 3. Mulivariate Analysis

In [ ]:
# Univariate Analysis for Numerical Column
df['referral_age'].describe()

In [ ]:
sns.histplot(data=df,x='referral_age',kde=True);

In [ ]:
sns.boxplot(data=df,x='referral_age');

In [ ]:
# Observations
# 1. The youngest referral is of 20 years
# 2. The senior most referral is of 65 years
# 3. Avregae age of referrals is 27 years
# 4. 75 % of referrals are 29 years or below
# 5. There is an outlier also

In [ ]:
# Univariate Analysis for Numerical Column
df['referral_aptitude_reasoning_score'].describe()

In [ ]:
sns.histplot(data=df,x='referral_aptitude_reasoning_score',kde=True);

In [ ]:
sns.boxplot(data=df,x='referral_aptitude_reasoning_score');

In [ ]:
# Univariate Analysis for Catagorical column
df['referral_gender'].value_counts()

In [ ]:
df['referral_gender'].value_counts(normalize=True)

In [ ]:
gender=sns.countplot(data=df, x='referral_gender');
for label in gender.containers:
  gender.bar_label(label)
plt.show()

In [ ]:
# Observations
# 1. There are 52.3 % males and 47.7% females in dataset

In [ ]:
# Bivariate Analysis
# 1. Numeric Vs Numeric
# 2. Catagorical Vs catagorical
# 3. Numeric Vs Categorical

In [ ]:
# 1. Bivariate Analysis : Numeric Vs Numeric
plt.scatter(df['referral_10_th_marks'],df['referral_12th_marks'])

In [ ]:
plt.scatter(df['referral_exp_in_years'],df['referral_current_salary']);

In [ ]:
# 2. Bivariate Analysis: Categorical Vs catagorical
sns.countplot(data=df, x='Emp_Salary_Grade', hue='Joined')

In [ ]:
pd.crosstab(df['Emp_Salary_Grade'],df['Joined'], margins=True)

In [ ]:
pd.crosstab(df['Emp_Salary_Grade'],df['Joined'], margins=True, normalize=True)

In [ ]:
# 3. Bivariate Analysis: Categorical Vs Numerical
sns.boxplot(data=df,x='Joined',y='referral_expected_sal')

In [ ]:
sns.pairplot(df)

In [ ]:
sns.heatmap(df.corr(),annot=True)