In [18]:
# Introduction to Pandas
# Pandas stands for 'Panel Data'
# It is the core library for data manipulation and data analysis.
# It consists of single and multidimensional data structures for data manipulation
# Single-dimensional data structures in Pandas are known as 'Series Object'
# Multi-dimensional data structure in Pandas are known as 'Data Frame'

In [20]:
# Importing the Pandas library
import pandas as pd

#Pandas Series Object

In [21]:
# Series object in one -dimensional labeled array

In [22]:
list1=[1,2,3,4,5]
s1=pd.Series(list1)
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [24]:
#checking the type of s1
type(s1)

pandas.core.series.Series

In [25]:
#Changing Index
s1=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
s1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [26]:
#Creating a series object with dictionary
s1=pd.Series({'a':100,'b':200,'c':300})
s1

a    100
b    200
c    300
dtype: int64

In [27]:
type(s1)

pandas.core.series.Series

In [28]:
#We can also change the index positions of series object created from dictionary
s1=pd.Series({'a':100,'b':200,'c':300},index=['b','c','d','a'])
s1

b    200.0
c    300.0
d      NaN
a    100.0
dtype: float64

In [29]:
'''
Extracting Individual elements
1. Extracting a single element
2. Extracting a sequence of elements from start
3. Extracting a sequence of elements from last
'''

'\nExtracting Individual elements\n1. Extracting a single element\n2. Extracting a sequence of elements from start\n3. Extracting a sequence of elements from last\n'

In [30]:
s1=pd.Series([1,2,3,4,5,6,7,8,9,10])

In [31]:
s1

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [32]:
s1[3]

4

In [33]:
s1[:4]

0    1
1    2
2    3
3    4
dtype: int64

In [34]:
s1[-3:]

7     8
8     9
9    10
dtype: int64

In [36]:
# Basic Math Operations on Series
# 1. Scalar Values
# 2. Series Obejcts

In [37]:
s1=pd.Series([1,2,3,4,5,6,7,8,9])
s1+5

0     6
1     7
2     8
3     9
4    10
5    11
6    12
7    13
8    14
dtype: int64

In [38]:
s1*5

0     5
1    10
2    15
3    20
4    25
5    30
6    35
7    40
8    45
dtype: int64

In [39]:
s1=pd.Series([1,2,3,4,5,6,7,8,9])
s2=pd.Series([10,20,30,40,50,60,70,80,90])
s1+s2

0    11
1    22
2    33
3    44
4    55
5    66
6    77
7    88
8    99
dtype: int64

In [40]:
s1*s2

0     10
1     40
2     90
3    160
4    250
5    360
6    490
7    640
8    810
dtype: int64

#Pandas Dataframe

In [41]:
# Dataframe is a 2-dimensional labeled data-structure
# A datafarme comprises of rows and columns

In [45]:
#Creating a dataframe (with dictionary)
df1=pd.DataFrame({'Name':['Amit','Ravi','Shree','Nitya'],'Marks':[80,57,87,90]})
df1

    Name  Marks
0   Amit     80
1   Ravi     57
2  Shree     87
3  Nitya     90

In [46]:
type(df1)

pandas.core.frame.DataFrame

In [60]:
#Creating DataFrame from files (.csv,.xls,.xlsx)
df1=pd.read_csv('sample_data/california_housing_test.csv')
df1

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [87]:
df1=pd.read_csv('sample_data/Iris.csv')
df1

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [49]:
#In-Build Functions of DataFrames
# 1. head() : Returns the top 5 rows of dataframe
df1.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [50]:
df1.head(2)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa

In [51]:
df1.head(7)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa

In [52]:
#2. tail() : Returns the last 5 rows of dataframe
df1.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [53]:
df1.tail(2)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [55]:
#shape(): Returns the number of rows and columns present in the dataframe
df1.shape

(150, 6)

In [56]:
print('No. of rows in dataframe : ',df1.shape[0])
print('\nNo. of columns in dataframe : ',df1.shape[1])

No. of rows in dataframe :  150

No. of columns in dataframe :  6

In [61]:
#4. describe() : Return the basic description of the dataframe (default only numeric columns)
# This is also called '5 point summary'/'Statistical summary'
df1.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,3000.000000,3000.00000,3000.000000,3000.000000,3000.000000,3000.000000,3000.00000,3000.000000,3000.00000
mean,-119.589200,35.63539,28.845333,2599.578667,529.950667,1402.798667,489.91200,3.807272,205846.27500
std,1.994936,2.12967,12.555396,2155.593332,415.654368,1030.543012,365.42271,1.854512,113119.68747
min,-124.180000,32.56000,1.000000,6.000000,2.000000,5.000000,2.00000,0.499900,22500.00000
25%,-121.810000,33.93000,18.000000,1401.000000,291.000000,780.000000,273.00000,2.544000,121200.00000
50%,-118.485000,34.27000,29.000000,2106.000000,437.000000,1155.000000,409.50000,3.487150,177650.00000
75%,-118.020000,37.69000,37.000000,3129.000000,636.000000,1742.750000,597.25000,4.656475,263975.00000
max,-114.490000,41.92000,52.000000,30450.000000,5419.000000,11935.000000,4930.00000,15.000100,500001.00000

In [62]:
# To view the summary if more numerical columns are present
df1.describe().T

,count,mean,std,min,25%,50%,75%,max
longitude,3000.0,-119.589200,1.994936,-124.1800,-121.810,-118.48500,-118.020000,-114.4900
latitude,3000.0,35.635390,2.129670,32.5600,33.930,34.27000,37.690000,41.9200
housing_median_age,3000.0,28.845333,12.555396,1.0000,18.000,29.00000,37.000000,52.0000
total_rooms,3000.0,2599.578667,2155.593332,6.0000,1401.000,2106.00000,3129.000000,30450.0000
total_bedrooms,3000.0,529.950667,415.654368,2.0000,291.000,437.00000,636.000000,5419.0000
population,3000.0,1402.798667,1030.543012,5.0000,780.000,1155.00000,1742.750000,11935.0000
households,3000.0,489.912000,365.422710,2.0000,273.000,409.50000,597.250000,4930.0000
median_income,3000.0,3.807272,1.854512,0.4999,2.544,3.48715,4.656475,15.0001
median_house_value,3000.0,205846.275000,113119.687470,22500.0000,121200.000,177650.00000,263975.000000,500001.0000

In [65]:
# 5. info : Return the data types, count, rows, coloumns, not null values of each column
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [ ]:
# Extrating individual rows and columns from dataframe using index numbers
# 1. iloc - index numbers
# 2. loc - names
df1.iloc[2,3]

In [ ]:
df1.iloc[0:3,0:2]

In [ ]:
df1.loc[0:3,("SepalLengthCm","SepalWidthCm")]

In [74]:
# Dropping rows/column from dataframe
# axis : attribute values tells python to drop row or column
# axis=1: to drop Column(s)
# axis=0: to drop row(s)
# It does not drop the column permanently

In [ ]:
df1.head(1)

In [ ]:
df1.drop("Species",axis=1)

In [ ]:
df1.head()

In [ ]:
#deleting rows
df1.drop([0,1,2,3],axis=0)

In [ ]:
df1.head()

In [ ]:
# To delete the rows /column permanently
# Inplace=True
df1.head()

In [82]:
df1.drop("Species",axis=1,inplace=True)

In [ ]:
df1.head()

In [84]:
#More Panads functions
# 1. mean()
# 2. median()
# 3. minimum()
# 4. maximum()
# 5. apply()
# 6. value_counts()
# 7. sort_values()

In [89]:
#1. mean()
df1.mean()

<ipython-input-89-b3869ec7b459>:2: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df1.mean()

Id               75.500000
SepalLengthCm     5.843333
SepalWidthCm      3.054000
PetalLengthCm     3.758667
PetalWidthCm      1.198667
dtype: float64

In [117]:
df1.mean()

<ipython-input-117-00fb6bfec183>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df1.mean()

Id               75.500000
SepalLengthCm     5.843333
SepalWidthCm      3.054000
PetalLengthCm     3.758667
PetalWidthCm      1.198667
dtype: float64

In [94]:
print(pd.__version_)

1.5.3

In [95]:
#print(libraryname.__version__)

In [96]:
df1.median()

<ipython-input-96-e41201014d8f>:1: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df1.median()

Id               75.50
SepalLengthCm     5.80
SepalWidthCm      3.00
PetalLengthCm     4.35
PetalWidthCm      1.30
dtype: float64

In [ ]:
df1.min()

In [ ]:
df1.min(numeric_only=True)

In [ ]:
df1.max()

In [ ]:
df1.max(numeric_only=True)

In [104]:
def double_values(i):
  return i*2

In [107]:
df1.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
df1[['SepalLengthCm','PetalLengthCm']].apply(double_values)

In [110]:
df1['Species'].value_counts()

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: Species, dtype: int64

In [111]:
df1['SepalLengthCm'].value_counts()

5.0    10
5.1     9
6.3     9
5.7     8
6.7     8
5.8     7
5.5     7
6.4     7
4.9     6
5.4     6
6.1     6
6.0     6
5.6     6
4.8     5
6.5     5
6.2     4
7.7     4
6.9     4
4.6     4
5.2     4
5.9     3
4.4     3
7.2     3
6.8     3
6.6     2
4.7     2
7.6     1
7.4     1
7.3     1
7.0     1
7.1     1
5.3     1
4.3     1
4.5     1
7.9     1
Name: SepalLengthCm, dtype: int64

In [115]:
df1.sort_values(by='SepalLengthCm',ascending=False)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
131,132,7.9,3.8,6.4,2.0,Iris-virginica
135,136,7.7,3.0,6.1,2.3,Iris-virginica
122,123,7.7,2.8,6.7,2.0,Iris-virginica
117,118,7.7,3.8,6.7,2.2,Iris-virginica
118,119,7.7,2.6,6.9,2.3,Iris-virginica
...,...,...,...,...,...,...
41,42,4.5,2.3,1.3,0.3,Iris-setosa
42,43,4.4,3.2,1.3,0.2,Iris-setosa
38,39,4.4,3.0,1.3,0.2,Iris-setosa
8,9,4.4,2.9,1.4,0.2,Iris-setosa
13,14,4.3,3.0,1.1,0.1,Iris-setosa